import { cn } from "~/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import "~/styles/globals.css";
import localfont from "next/font/local";
import { SideBar } from "~/components/side-bar";
import { Header } from "~/components/header";

const siteFont = localfont({
  src: "../../public/notosan/static/NotoSans_SemiCondensed-Light.ttf",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            siteFont.className,
            "flex items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] ",
          )}
        >
          <main className="mx-auto flex w-[80%]  overflow-hidden ">
            <SideBar />
            <div className="grow">
              <Header />
              {children}
            </div>
          </main>
          {modal}
          <div id="modal-root" />
        </body>
      </html>
    </ClerkProvider>
  );
}
